### ISSUE TITLE
リクエストを論理的な構造体にラップする

### ISSUE THREAD

**Issue by YusukeHosonuma** [YusukeHosonuma/rust-server#7]

**Comment by MiyasakaKazutoshi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [task](https://trello.com/c/AP6RRlSk/2-task)

**Comment by MiyasakaKazutoshi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [task](https://trello.com/c/AP6RRlSk/2-task)
